export const abi = [
    "function createDraftCertificate(string certId, string uri, address expectedClaimer, uint256 expireAt) external",
    "function createBatchDraftCertificates(string[] certIds, string[] uris, address[] claimers, uint256[] expireAts) external",
    "function updateExpectedClaimer(string certId, address newClaimer) external",
    "function batchUpdateExpectedClaimers(string[] certIds, address[] newClaimers) external",
    "function claimCertificate(string certId) external",
    "function claimBatchCertificates(string[] certIds) external",
    "function updateCertificateURI(string certId, string newURI) external",
    "function revokeCertificate(string certId) external",
    "function verifyCertificate(string certId) external view returns (bool valid, uint8 status, address currentOwner, string uri, uint256 issuedAt, uint256 expireAt)",
    "function isValid(string certId) public view returns (bool)",
    "function ownerOf(uint256 tokenId) external view returns (address)",
    "function _exists(uint256 tokenId) public view returns (bool)",
    "event CertificateCreated(string certId, address expectedClaimer, string uri, uint256 expireAt)",
    "event CertificateClaimed(string certId, address claimer, uint256 tokenId, uint256 issuedAt)",
    "event CertificateRevoked(string certId)",
    "event CertificateUpdated(string certId, string newURI)",
    "event ExpectedClaimerUpdated(string certId, address newClaimer)",
    "event CertificateTransferred(string certId, address from, address to)"
];
